/**
 * $Id: cxxhtc_defs.h 133 2010-02-08 04:25:43Z dantld $
 * C++HTC namespaces definitions.
 */
#ifndef __CXX_HTC__DEFS__LIBRARY__H__
#define __CXX_HTC__DEFS__LIBRARY__H__

#define CXXHTC_NAMESPACE kisc
#define CXXHTC CXXHTC_NAMESPACE
#define BEGIN_CXXHTC_NAMESPACE namespace CXXHTC_NAMESPACE {
#define END_CXXHTC_NAMESPACE }

#define CXXHTC_UTIL_NAMESPACE util
#define BEGIN_CXXHTC_UTIL_NAMESPACE namespace CXXHTC_UTIL_NAMESPACE {
#define END_CXXHTC_UTIL_NAMESPACE }

#define CXXHTC_CONFIG_NAMESPACE config
#define BEGIN_CXXHTC_CONFIG_NAMESPACE namespace CXXHTC_CONFIG_NAMESPACE {
#define END_CXXHTC_CONFIG_NAMESPACE }

#define CXXHTC_CRYPTO_NAMESPACE crypto
#define BEGIN_CXXHTC_CRYPTO_NAMESPACE namespace CXXHTC_CRYPTO_NAMESPACE {
#define END_CXXHTC_CRYPTO_NAMESPACE }

#endif // __CXX_HTC__DEFS__LIBRARY__H__
